apiVersion: apps/v1
kind: Deployment
metadata:
  name: follower
spec:
  replicas: 2
  selector:
    matchLabels:
      app: follower
  template:
    metadata:
      labels:
        app: follower
    spec:
      containers:
        - name: follower
          image: distributed-system:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ROLE
              value: "follower"
            - name: SERVER_PORT
              value: "8080"
          livenessProbe:
            httpGet:
              path: /replica/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /replica/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10